### ISSUE TITLE
Screenshots/GIf not visible of 3D flip card

### ISSUE THREAD

**Issue by mudit023** [mudit023/templates#49] opened 2022-04-15 19:34 UTC
Screenshots are not visible in the [3D flip card README.md](https://github.com/mudit023/templates/blob/main/3D%20Flip%20Card%20on%20Hover%20-%20Programing-School/README.md)
They are added in the template [folder](https://github.com/mudit023/templates/tree/main/3D%20Flip%20Card%20on%20Hover%20-%20Programing-School).

**Comment by Programing-School** [comment] 2022-04-15 19:37
Please if the issue is for a problem of my templates please mention me

**Comment by Programing-School** [comment] 2022-04-15 19:38
And Assign it to me

**Comment by mudit023** [comment] 2022-04-15 19:50
If you want to solve it, you can.

**Comment by Programing-School** [comment] 2022-04-15 19:51
> If you want to solve it, you can.

Approve the pull request to create another

**Comment by Programing-School** [comment] 2022-04-15 19:51
I solve it

**Comment by Programing-School** [comment] 2022-04-16 13:27
Accept The Pull request and close this Issue

**Comment by mudit023** [comment] 2022-04-16 14:41
Can you try to add a GIF instead of a screenshot because your template contains animation

**Comment by Programing-School** [comment] 2022-04-16 14:42
Ok, I will try

**Comment by Programing-School** [comment] 2022-04-16 15:03
> Can you try to add a GIF instead of a screenshot because your template contains animation

Done

**Comment by mudit023** [comment] 2022-04-16 17:01
Merged

**Closed** 2022-04-16 17:01 UTC
Labels: bug, documentation, good first issue
